### ISSUE TITLE
Reporting - Abilities presented in MITRE Navigator

### ISSUE THREAD

**Issue by ramus82** [mitre/stockpile#349]
For reporting purposes.

Script which will generate from already developed abilities JSON file compatible with MITRE Navigator (https://mitre-attack.github.io/attack-navigator/enterprise/) where the results can be presented.

**Comment by ramus82** [comment]
Already opened branch - "navigator".

**Comment by wbooth** [comment]
@ramus82 the compass plugin: https://github.com/mitre/compass should have the functionality you are looking for
