### ISSUE TITLE
What the different between Find domain controller and Discover domain controller?

### ISSUE THREAD

**Issue by dumprop** [mitre/stockpile#487]
In stockpile we have two abilities: [Find domain controller](https://github.com/mitre/stockpile/blob/master/data/abilities/discovery/b22b3b47-6219-4504-a2e6-ae8263e49fc3.yml) and [Discover domain controller](https://github.com/mitre/stockpile/blob/master/data/abilities/discovery/26c8b8b5-7b5b-4de1-a128-7d37fb14f517.yml)? (they are very similar)
<img width="1185" src="https://user-images.githubusercontent.com/34004367/95572203-49ef6380-0a32-11eb-9fdb-5fd615a3ed98.png">

**Comment by wbooth** [comment]
Looks like a duplicate: if you want to put up a change to fix we can get that merged in.

**Comment by dumprop** [comment]
Done, accept it with "hacktoberfest-accepted", please
