### ISSUE TITLE
Update technique id of abilities

### ISSUE THREAD

**Issue by dumprop** [mitre/stockpile#489]
Some abilities are still not updated according to the new attck matrix
[Example in stockpile](https://github.com/mitre/stockpile/blob/master/data/abilities/command-and-control/0ab383be-b819-41bf-91b9-1bd4404d83bf.yml) (there "T1071") and [similar in atomic](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1071.001/T1071.001.yaml) (there "T1071.001")
Also in T1071 only one ability from stockpile
<img width="1058" src="https://user-images.githubusercontent.com/34004367/96298695-8d7e3a80-0ffb-11eb-803e-ab389da74307.png">
Although in T1071.001 already three abilities from atomic with the same meaning
<img width="1058" src="https://user-images.githubusercontent.com/34004367/96298776-b56d9e00-0ffb-11eb-9445-08d88877a62d.png">
So, I think we should update all abilities according new numeration (with sub technique) since using old numeration is a bit confusing

**Comment by wbooth** [comment]
Thanks, we can update those in stockpile, the ones from atomic come from the atomic red team, which we don't maintain so would need them to update. 
If you want to put up a PR for the ones in stockpile, I'd be happy to merge it in. 
Thanks for looking into this!

**Comment by dumprop** [comment]
Done, updated all abilities in stockpile, which obviously disperse (according atomic and mitre numeration)
