### ISSUE TITLE
Possible duplicates in abilities 

### ISSUE THREAD

**Issue by dumprop** [mitre/stockpile#510]
We have two "Start 54ndc47 (WMI)" abilities  ([1](https://github.com/mitre/stockpile/blob/master/data/abilities/execution/ece5dde3-d370-4c20-b213-a1f424aa8d03.yml) and [2](https://github.com/mitre/stockpile/blob/master/data/abilities/execution/2a32e46f-5346-45d3-9475-52b857c05342.yml))
I think the first can be removed because it looks like the second and no usage in any adversary

**Comment by dumprop** [comment]
Also I a little bit confused with [Find System Network Connections](https://github.com/mitre/stockpile/blob/master/data/abilities/discovery/638fb6bb-ba39-4285-93d1-7e4775b033a8.yml) and [System Network Connections Discovery](https://github.com/mitre/stockpile/blob/master/data/abilities/discovery/613e0ffb-e6e8-4e86-b35d-10edd232679d.yml)
Probably they can be merged

**Comment by wbooth** [comment]
thanks we'll review

**Comment by ArtificialErmine** [comment]
Thanks for bringing this to our attention, @dumprop. We've consolidated both of the duplicated abilities you pointed out, sorry about the delay.
